name: Create Release

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check and set HMCL version
        run: |
          export HMCL_VERSION=`echo ${{ github.ref }} | awk '{print substr($0,12)}'`
          echo "::set-env name=HMCL_VERSION::$HMCL_VERSION"

          if [ -z `echo "3.3.182" | grep "^[0-9]\.[0-9]\.[0-9]\{3\}\$"` ]; then
            exit 1
          fi

          echo "::set-env name=HMCL_BUILD_NUMBER::`echo $HMCL_VERSION | awk '{print substr($0,5)}'`"
      - name: Download artifacts
        run: |
          wget "$DOWNLOAD_BASE_URL/HMCL-$HMCL_VERSION.exe"
          wget "$DOWNLOAD_BASE_URL/HMCL-$HMCL_VERSION.exe.sha1"
          wget "$DOWNLOAD_BASE_URL/HMCL-$HMCL_VERSION.jar"
          wget "$DOWNLOAD_BASE_URL/HMCL-$HMCL_VERSION.jar.sha1"
        env:
          DOWNLOAD_BASE_URL: https://ci.huangyuhui.net/job/HMCL/${{ env.HMCL_BUILD_NUMBER }}/artifact/HMCL/build/libs
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            HMCL-${{ env.HMCL_VERSION }}.exe
            HMCL-${{ env.HMCL_VERSION }}.exe.sha1
            HMCL-${{ env.HMCL_VERSION }}.jar
            HMCL-${{ env.HMCL_VERSION }}.jar.sha1